### ISSUE TITLE
No appropriate version found

### ISSUE THREAD

**Issue by decaf-dev** [mahmudz/obsidian-favorite-plugin#1]
I get this error when trying to download the plugin

<img width="224" alt="image" src="https://github.com/mahmudz/obsidian-favorite-plugin/assets/40307803/009cd132-b2f2-45f9-9b6a-07c6794fd0e3">

It looks like you're missing a version key in the `manifest.json`

**Comment by mahmudz** [comment]
Please re-install. I fixed it.

**Comment by decaf-dev** [comment]
It's working. Thanks
