### ISSUE TITLE
Support for phone versions

### ISSUE THREAD

**Issue by aderchox** [mahmudz/obsidian-favorite-plugin#2]
Hi, this seems not to be working on Obsidian Android. Or at least I cannot find the heart icon. If it's not supported, do you have any plans for adding support?
Apart from the difference you've written in the README, I believe this plugin can be extremely useful because the Obsidian's built-in Bookmarks feature is [known to be buggy](https://forum.obsidian.md/t/sync-everything-but-bookmarks-dont-sync/61683) in sync, so even adding a single "favorites" bookmark that works cross-devices would be a popular plugin.

**Comment by mahmudz** [comment]
@aderchox Support for mobile added.
Settings option is missing now, I will add it as soon as i can manage some time.
